src/com/seafile/seadroid2/ui/fragment/ReposFragment.java
exception occurs when
1. network connetion very slow
2. navigate among repos very fast
error log
```
java.lang.ClassCastException: com.seafile.seadroid2.data.SeafRepo cannot be cast to com.seafile.seadroid2.data.SeafDirent
E/AndroidRuntime(14685): 	at com.seafile.seadroid2.ui.fragment.ReposFragment.onListItemClick(ReposFragment.java:355)
E/AndroidRuntime(14685): 	at android.support.v4.app.ListFragment$2.onItemClick(ListFragment.java:58)
E/AndroidRuntime(14685): 	at android.widget.AdapterView.performItemClick(AdapterView.java:298)
E/AndroidRuntime(14685): 	at android.widget.AbsListView.performItemClick(AbsListView.java:1139)
E/AndroidRuntime(14685): 	at android.widget.AbsListView$PerformClick.run(AbsListView.java:2856)
E/AndroidRuntime(14685): 	at …
```
=> SeafRepo cast SeafDirent exception

src/com/seafile/seadroid2/SSLSeafileSocketFactory.java, src/com/seafile/seadroid2/SSLTrustManager.java
* Enable TLS 1.1+
* Overwrite Android's default cipherlist with a more secure one.
(see patches for more detailed explanations)
=> TLS protocol and cipher list improvements

src/com/seafile/seadroid2/ui/activity/AccountDetailActivity.java
fix Content of the password and mail field are switched after rotating in the 'add account' view #218
=> save and restore text on screen rotate

src/com/seafile/seadroid2/monitor/SeafileMonitor.java
1. login an account
2. browser the library list, open one library in order to download a file later
3. go to overflow menu, click `Accounts` to open Accounts List
4. long press one account, delete it
5. press back button (not home up button to top left corner) to go back to the library list as described in step 2.
6. click a file to download
7. the app crashes
```
E/AndroidRuntime(20551): 	at com.seafile.seadroid2.monitor.SeafileMonitor.onFileDownloaded(SeafileMonitor.java:59)
E/AndroidRuntime(20551): 	at com.seafile.seadroid2.monitor.FileMonitorService$3.onReceive(FileMonitorService.java:134)
E/AndroidRuntime(20551): 	at android.support.v4.content.LocalBroadcastManager.executePendingBroadcasts(LocalBroadcastManager.java:297)
E/AndroidRuntime(20551): 	at …
```
=> fix monitor file download null pointer exception

res/values/strings.xml, src/com/seafile/seadroid2/ui/dialog/SslConfirmDialog.java
This exception occurs when failed to get CertificateInfo (null pointer) for an specific account at runtime. 
In this case, SslConfirmDialog can\`t show the certificate details info.
```
java.lang.NullPointerException: Attempt to invoke virtual method 'javax.security.auth.x500.X500Principal java.security.cert.X509Certificate.getSubjectX500Principal()' on a null object reference
at com.seafile.seadroid2.data.CertificateInfo.getSubjectName(CertificateInfo.java:40)
at com.seafile.seadroid2.ui.dialog.SslConfirmDialog.onCreateDialog(SslConfirmDialog.java:94)
at android.support.v4.app.DialogFragment.getLayoutInflater(DialogFragment.java:295)
at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:925)
at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager …
```
=> fix certificate null pointer exception

AndroidManifest.xml, THIRD_PARTY_LICENSE.md, src/com/seafile/seadroid2/SeadroidApplication.java, src/com/seafile/seadroid2/gesturelock/AbstractAppLock.java, src/com/seafile/seadroid2/gesturelock/AppLockManager.java, src/com/seafile/seadroid2/gesturelock/DefaultAppLock.java, src/com/seafile/seadroid2/ui/activity/BrowserActivity.java, src/com/seafile/seadroid2/ui/activity/SeafilePathChooserActivity.java
Unfortunately there is no an elegant way to intercept the activity life cycle methods except by having all activities extend some base class. But this is not ideal - activity hierarchy will be too messy. [as mentioned from here](https://github.com/BoD/android-activitylifecyclecallbacks-compat).
This PR mainly based on [Android-PasscodeLock](https://github.com/wordpress-mobile/Android-PasscodeLock) from [wordpress-mobile](https://github.com/wordpress-mobile). As a workaround it only support Android API 14 upwards.
=> show gesturelock when resume from multitask window

src/com/seafile/seadroid2/ui/activity/AccountsActivity.java
fix load avatar null pointer #251 
this exception occurs when server did\`t response.
to fix it, skip the error and continue to process next.
=> fix load avatart null pointer

src/com/seafile/seadroid2/ui/fragment/TransferTaskFragment.java
fix transfer task list empty when unlock the screen bug.
* If your Activity wants to be interacting with the Service the entire time it is running (for example maybe it can retrieve some data from a network for you and will return the data when ready and you want to allow this to happen while in the background so if the user returns you will have the data ready), then onCreate()/onDestroy() is probably appropriate. Note that the semantics here is that the entire time your Activity is running it needs the Service, so if this Service is running in another process then you have increased the weight of it and made it more likely for it to be killed while in the background.
* If your Activity is only interested in working with the  Service while visible, then onStart()/onStop() is appropriate. …
=> bind service in onStart

src/com/seafile/seadroid2/SSLSeafileSocketFactory.java
RFC 7465 recommends to not use RC4 cyphers anymore.
Firefox 36+ disables it as well (https://www.mozilla.org/en-US/firefox/36.0/releasenotes/).
This patch removes all RC4 cyphersuites from the list offered to the server.
=> Disable insecure RC4 cyphersuites

src/com/seafile/seadroid2/transfer/DownloadTaskManager.java, src/com/seafile/seadroid2/ui/activity/BrowserActivity.java
Download folder feature does not work #290
* login Seafile account
* navigate into repo like "Seafile-design"
* navigate into subfolders like "/new-design/seahub/v5.0"
* click overflow menu and choose "Download folder"
* toast the message "Network connection error, please try again later!", which failed downloading the folder
the requested path parameter is incorrect.
WRONG
dirPath: `/new-design/seahub/v5.0`
direntName:`/new-design/seahub`
assembled requested path:`/new-design/seahub/v5.0/new-design/seahub` (not exist)
RIGHT
dirPath: `/new-design/seahub/v5.0`
direntName:`v5.0`
assembled requested path:`/new-design/seahub/v5.0`
=> fix download folder not working bug

src/com/seafile/seadroid2/transfer/TransferManager.java
CopyOnWriteArrayList has several downsides
* crash when removing items caused by UnsupportedOperationException 
* updating (e.g. add or set) this collection a lot will [kill performance](http://stackoverflow.com/a/17853225/3962551)
crash log
```
java.lang.UnsupportedOperationException
E/AndroidRuntime(19137): 	at java.util.concurrent.CopyOnWriteArrayList$CowIterator.remove(CopyOnWriteArrayList.java:744)
E/AndroidRuntime(19137): 	at com.seafile.seadroid2.transfer.TransferManager.removeByState(TransferManager.java:135)
E/AndroidRuntime(19137): 	at com.seafile.seadroid2.transfer.TransferService.removeAllUploadTasksByState(TransferService.java:80)
E/AndroidRuntime(19137): 	at com.seafile.seadroid2.ui.fragment.UploadTaskFragment.onContextItemSelected(UploadTaskFragment.java:79)
```
To solve …
=> Fix concurrent exceptions

src/com/seafile/seadroid2/data/DataManager.java, src/com/seafile/seadroid2/ui/activity/BrowserActivity.java, src/com/seafile/seadroid2/util/Utils.java
Reasoning: Temp files aren't deleted after upload.
If the user tries to upload the same file twice,
the temp file cannot be created again, causing an
throw new RuntimeException("could not create temporary file");
We can't delete or overwrite the existing temp file, as the upload
might still be in progress.
There are other ways to fix this issue, but this is the simplest solution,
as far as I can see.
=> fix: error when uploading same file again

.travis.yml, AndroidManifest.xml, README.md, pom.xml, project.properties, res/values/strings.xml, src/com/seafile/seadroid2/SeafConnection.java, src/com/seafile/seadroid2/account/Account.java, src/com/seafile/seadroid2/account/AccountDBHelper.java, src/com/seafile/seadroid2/data/DataManager.java, src/com/seafile/seadroid2/data/SeafStarredFile.java, src/com/seafile/seadroid2/provider/DocumentIdParser.java, src/com/seafile/seadroid2/provider/ProviderUtil.java, src/com/seafile/seadroid2/provider/SeafileProvider.java
These are a couple of patches to the Seafile Document Provider.
I've split them into a patchset for easier reviewing. However each patch by itself will very likely not compile.
* Support writing (uploading) files
* Support creating files/directories
* Show starred files
* Improve repository list: use seafile icons for repositories, show descriptions
* fix: don't allow user to enter encrypted repos. that was previously broken.
* improve account (root) list: display account email adress in 2nd line
* use a thread pool for concurrent tasks (instead of spawning a new Thread each time)
* remove verbose FileNotFoundExceptions (with translated strings). they aren't shown to the user anyway.
* some refactoring
* some small fixes
see [test …
=> Document Provider: Write support and other changes

src/com/seafile/seadroid2/monitor/SeafileMonitor.java
crash log 
```
at com.seafile.seadroid2.monitor.SeafileMonitor.removeObserver(SeafileMonitor.java:51)
at com.seafile.seadroid2.monitor.SeafileMonitor.stopMonitorFilesForAccount(SeafileMonitor.java:42)
at com.seafile.seadroid2.monitor.FileMonitorService.removeAccount(FileMonitorService.java:97)
at com.seafile.seadroid2.ui.activity.AccountsActivity.onContextItemSelected(AccountsActivity.java:213)
at android.app.Activity.onMenuItemSelected(Activity.java:2620)
at android.support.v4.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:361)
at com.actionbarsherlock.app.SherlockFragmentActivity.onMenuItemSelected(SherlockFragmentActivity.java:210)
at com.android.internal.policy.impl.PhoneWindow$DialogMenuCallback.onMenuItemSelected(PhoneWindow.java:4129) …
```
=> fix SeafileMonitor removeObserver NPE

src/com/seafile/seadroid2/ui/activity/BrowserActivity.java
error log
```
at com.seafile.seadroid2.ui.activity.BrowserActivity.onFileUploadFailed(BrowserActivity.java:1467)
at com.seafile.seadroid2.ui.activity.BrowserActivity.access$1000(BrowserActivity.java:86)
at com.seafile.seadroid2.ui.activity.BrowserActivity$TransferReceiver.onReceive(BrowserActivity.java:1514)
at android.support.v4.content.LocalBroadcastManager.executePendingBroadcasts(LocalBroadcastManager.java:297)
at android.support.v4.content.LocalBroadcastManager.access$000(LocalBroadcastManager.java:46)
at android.support.v4.content.LocalBroadcastManager$1.handleMessage(LocalBroadcastManager.java:116)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:146)
at …
```
=> fix app crash when onFileUploadFailed was called

src/com/seafile/seadroid2/ui/activity/BrowserActivity.java
Fix on file uploaded null pointer exception
error log 
```
at com.seafile.seadroid2.ui.activity.BrowserActivity.onFileUploaded(BrowserActivity.java:1612)
at com.seafile.seadroid2.ui.activity.BrowserActivity.access$1400(BrowserActivity.java:90)
at com.seafile.seadroid2.ui.activity.BrowserActivity$TransferReceiver.onReceive(BrowserActivity.java:1673)
at android.support.v4.content.LocalBroadcastManager.executePendingBroadcasts(LocalBroadcastManager.java:297)
at android.support.v4.content.LocalBroadcastManager.access$000(LocalBroadcastManager.java:46)
at android.support.v4.content.LocalBroadcastManager$1.handleMessage(LocalBroadcastManager.java:116)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:137)
at …
```
=> Fix on file uploaded null pointer exception

src/com/seafile/seadroid2/cameraupload/CameraUploadConfigActivity.java
getActionBar is a method of api 11, so change to call getSupportActionBar instead.
Also make the class extends SherlockFragmentActivity to keep consistent with other classes.
error log
```
java.lang.NoSuchMethodError: com.seafile.seadroid2.cameraupload.CameraUploadConfigActivity.getActionBar
at com.seafile.seadroid2.cameraupload.CameraUploadConfigActivity.onCreate(CameraUploadConfigActivity.java:57)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1047)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1615)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:1667)
at android.app.ActivityThread.access$1500(ActivityThread.java:117)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:935)
at …
```
=> fix getActionBar NoSuchMethodError

src/com/seafile/seadroid2/ui/adapter/SeafItemAdapter.java
error log
```
java.lang.IllegalArgumentException: the bind value at index 3 is null
E/AndroidRuntime(10496): 	at android.database.sqlite.SQLiteProgram.bindString(SQLiteProgram.java:164)
E/AndroidRuntime(10496): 	at android.database.sqlite.SQLiteProgram.bindAllArgsAsStrings(SQLiteProgram.java:200)
E/AndroidRuntime(10496): 	at android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:47)
E/AndroidRuntime(10496): 	at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1448)
E/AndroidRuntime(10496): 	at android.database.sqlite.SQLiteDatabase.queryWithFactory(SQLiteDatabase.java:1295)
E/AndroidRuntime(10496): 	at android.database.sqlite.SQLiteDatabase.query(SQLiteDatabase.java:1166)
E/AndroidRuntime(10496): 	at …
```
=> fix IllegalArgumentException

res/values/strings.xml, src/com/seafile/seadroid2/ui/adapter/TransferTaskAdapter.java, src/com/seafile/seadroid2/ui/fragment/DownloadTaskFragment.java, src/com/seafile/seadroid2/ui/fragment/UploadTaskFragment.java
When failed downloading a file, the failed info, like Chinese translation is incorrect.
The reason is that the original language resource is ambiguous, which is error-prone when contributors trying to translate their languages.
=> correct download failed info

src/com/seafile/seadroid2/ui/adapter/SeafItemAdapter.java, src/com/seafile/seadroid2/ui/adapter/StarredItemAdapter.java
As noted by the [document of Universal Image Loader](https://github.com/nostra13/Android-Universal-Image-Loader#usage),
>NOTE: Use drawable:// only if you really need it! Always consider the native way to load drawables - ImageView.setImageResource(...) instead of using of ImageLoader.
=> use native way to load drawables

src/com/seafile/seadroid2/ui/activity/BrowserActivity.java, src/com/seafile/seadroid2/ui/dialog/OpenAsDialog.java
as [normalizeMimeType](http://developer.android.com/reference/android/content/Intent.html#normalizeMimeType\(java.lang.String\)) and [setDataAndType](http://developer.android.com/reference/android/content/Intent.html#setDataAndType\(android.net.Uri, java.lang.String\)) said from official documents
>
1. All MIME types received from outside Android
(such as user input, or external sources like Bluetooth, NFC, or the Internet)
should be normalized before they are used to create an Intent.
2. MIME type and Uri scheme matching in the Android framework is case-sensitive, unlike the formal RFC definitions.
As a result, you should always write these elements with lower case letters,
or use normalizeMimeType(String) or normalizeScheme() or setDataAndTypeAndNormalize(Uri, String)
to ensure that …
=> refactor open files method

src/com/seafile/seadroid2/SSLTrustManager.java, src/com/seafile/seadroid2/account/Account.java
Matches the server host name without port information against the
retrieved certificate. See
https://forum.seafile-server.org/t/bug-in-seafile-android-app-1-7-1/1911/3
=> Fix bug in certificate validation

src/com/seafile/seadroid2/ui/activity/GalleryActivity.java, src/com/seafile/seadroid2/ui/fragment/ReposFragment.java
encrypted repo doesn`t support pic thumbnails, when user clicking a pic under encrypted repo,
directly download the file and open it by sending a system intent.
=> download pics directly in encrypted repo

src/com/seafile/seadroid2/util/Utils.java
Files with a ".dmg" extension (e.g. Sublime Text Build 3083.dmg) are not correctly recognized by current mime type check logic.
The correct mime type for files with a ".dmg" extension should be "application/x-apple-diskimage", instead of "image", this error will lead up to a incorrect thumbnail preview, and incorrect behaviour in gallery.
=> fixed an mime type check error

src/com/seafile/seadroid2/data/SeafPhoto.java, src/com/seafile/seadroid2/ui/WidgetUtils.java, src/com/seafile/seadroid2/ui/activity/BrowserActivity.java, src/com/seafile/seadroid2/ui/activity/GalleryActivity.java, src/com/seafile/seadroid2/ui/activity/SearchActivity.java, src/com/seafile/seadroid2/ui/adapter/GalleryAdapter.java
Photos shown in gallery are calculated by local cached files if they already exist, otherwise files will be asynchronously downloaded first.
=> redesign gallery to avoid creating multiple thumbnails on server side

AndroidManifest.xml, src/com/seafile/seadroid2/ui/activity/BrowserActivity.java
I have found that to restore previous browsing state instead of simply recreated a new Activity (Launcher Activity), one solution might be
1. set `android:launchMode="singleTop"` in AndroidManifest.xml
2. comment the method [protected void onNewIntent(Intent intent)](https://github.com/haiwen/seadroid/blob/master/src/com/seafile/seadroid2/ui/activity/BrowserActivity.java#L623) in `BrowserActivity.java`.
But the potential risk is that **step 2** may introduce new bugs since it commented the code segment. So the following maintainer who are reading this should move the code segment in `onNewIntent` method to some suitable place, then you comment the method with no worry.
Reference
---
>
On some devices, pressing the launcher icon results in the current task being resumed, on others it …
=> restore state of previous browsing

res/values/strings.xml
There are precise official [tutorials](http://developer.android.com/guide/topics/resources/string-resource.html#Plurals) about how to manage plurals in Android world. 
But things get a little bit tough when it comes to use Transifex to manage internationalizations, especially when `xliff` tag was used, because when pull/export the translations, `xliff` tags are wrapped by quotes and all quotes inside xliff tag are escaped. See [Xliff in android xml files](Xliff in android xml files) and [xliff tags are not supported and strings containing them are dropped](https://github.com/transifex/transifex/issues/236).
Solutions for that
* use `<![CDATA[]]>` to avoid escaping
* or drop the `xliff` tag
For plurals, the source string (for pushing) looks like below
```
<plurals …
```
=> [i18n] simplify plurals management procedure

src/com/seafile/seadroid2/ui/fragment/SettingsFragment.java
getAccountInfo() might throw a com.github.kevinsawicki.http.HttpRequest$HttpRequestException
if DNS lookup fails. An uncatched exception in an AsyncTask causes the whole app to crash,
so better catch all of them.
Steps to reproduce:
1. start android emulator
2. disable network on your computer
3. start seafile in emulator
4. go to settings page
5. crash
Note that the "isNetworkOn()" check makes the bug not reproducible in "flight mode".
=> Catch missing exceptions in AsyncTask

src/com/seafile/seadroid2/account/Account.java, src/com/seafile/seadroid2/provider/SeafileProvider.java
Previously it was assumed that SeafileProvider.queryRoots() would be called
before any of the other SeafileProvider.queryXXX() methods. That was a mistake.
At least SeafileProvider.queryDocument() might actually be called earlier.
This can cause problems if the Android OS has just been freshly rebooted and
the SAF is used for the first time. In that case
SeafileProvider.isReachable
will still be empty. Thus doing an
SeafileProvider.isReachable.get(account)
will return null. That breaks thinks, as can be witnessed e.g. by trying to use
latest Keepass2Android release with Seadroid after a fresh reboot.
This patches fixes that issue by converting the HashMap into a Set
(which is a more fitting data structure anyway).
(Making Account "Comparable" is just necessary to make the …
=> bugfix: early SAF usage by app might fail

res/layout-sw600dp/list_item_entry.xml, res/layout-xlarge/list_item_entry.xml, res/layout/list_item_entry.xml
Optimized item layout of slide expandable listview in order to fix the messy layout under an encrypted repo. Position items in a rectangle area with same width, see the preview as below.
=> optimize item layout of slide expandable listview

src/com/seafile/seadroid2/ui/activity/AccountDetailActivity.java
This will force the keyboard to be hidden in all situations. In some cases you will want to pass in InputMethodManager.HIDE_IMPLICIT_ONLY as the second parameter to ensure you only hide the keyboard when the user didn't explicitly force it to appear (by holding down menu).
=> hide the soft keyboard after cliked login button

src/com/seafile/seadroid2/ui/fragment/ActivitiesFragment.java
If use `startActivityForResult` in Fragment, it will not call the `onActivityResult` of the parent Activity, so the file will not be opened after downloaded. 
The right way is to use `getBrowserActivity().startActivityForResult(intent, BrowserActivity.DOWNLOAD_FILE_REQUEST);`
=> fixed bug when files not opened in ACTIVITIES tab

src/com/seafile/seadroid2/account/Account.java, src/com/seafile/seadroid2/ui/activity/AccountDetailActivity.java, src/com/seafile/seadroid2/ui/activity/AccountsActivity.java, src/com/seafile/seadroid2/ui/activity/BrowserActivity.java, src/com/seafile/seadroid2/ui/activity/UnlockGesturePasswordActivity.java
When tapping on the Seadroid Launcher icon, Seadroid currently always reverts back to
its "Home screen" (the list of repositories). Even if Seadroid was
already running and the user had already entered a specific folder.
This behaviour differs from most other apps. Usually the state of the app is preserved
if one re-enters it via the Launcher app.
This patch tries to do exactly that. The key place is BrowserActivity.onNewIntent()
In this method we have to decide whether to kill the old BrowserActivity and create a new
one; or to just keep the old one running.
Previously this was decided on the given account information. However this does not work
with the Launcher, as the account info is null if the intent comes from the Launcher.
I decided to use the Intent category/action for making …
=> Remember browse position when re-entering Seadroid via Launcher icon

build.gradle
Current Seadroid master breaks when freshly installed on Android 6.0 devices.
Steps to reproduce:
1. Use an Android 6.0 device
2. Delete Seadroid app (*)
3. build .apk
4. install .apk on device (e.g. via file manager) - you will not be shown list of required permissions on .apk install
5. create account in Seadroid
6. BrowseActivity will crash as Seadroid is lacking WRITE_EXTERNAL_STORAGE permission.
This patch fixes this issue by lowering the target level to 22. See commit message for more details.
(*) upgrading Seadroid will work, as previously granted permissions remain intact.
=> Fix crash on Android 6.0 when freshly installed

app/src/main/java/com/seafile/seadroid2/ui/activity/BrowserActivity.java, app/src/main/res/values/strings.xml, build.gradle
fix #475 
It might make sense to ask for all of those permissions as soon as the app launches.
If the user is running Android 6.0 (API level 23) or later, the user has to grant your app its permissions while they are running the app.
useful links
1. https://www.google.com/design/spec/patterns/permissions.html?utm_campaign=runtime-permissions-827&utm_source=dac&utm_medium=blog#
2. http://developer.android.com/training/permissions/best-practices.html#dont-overwhelm
=> Ask storage permission for Android_M after app launched

app/src/main/res/layout/file_activity.xml, app/src/main/res/values-v21/styles.xml, app/src/main/res/values/styles.xml
fix `java.lang.UnsupportedOperationException` reported on Google Play Console.
use `Base.Widget.AppCompat.Button` as parent style to style negative buttons.
this should fix #478
=> Fix crash when render material buttons on pre-L devices

app/src/main/java/com/seafile/seadroid2/ui/HackyViewPager.java, app/src/main/java/com/seafile/seadroid2/ui/activity/GalleryActivity.java, app/src/main/res/layout/gallery_activity_layout.xml
Steps to reproduce (tested on Android 5.1 and 6.0):
1. open image within seafile
2. zoom out with 3+ fingers aggressively multiple times
3. after 5-10 zoom-out gestures, the activity will crash (see exception below)
The cause is a apparently bug in the Android framework, which causes a crash when using
the PhotoView library. More details on the bug can be found in:
* https://github.com/chrisbanes/PhotoView#issues-with-viewgroups
* https://github.com/chrisbanes/PhotoView/issues/206
The workaround is to use a modified ViewPager provided by the author
of PhotoView.
01-31 23:29:16.255 10549-10549/? E/AndroidRuntime: FATAL EXCEPTION: main
Process: com.seafile.seadroid2, PID: 10549
java.lang.IllegalArgumentException: pointerIndex out of range
at …
=> fix a multitouch zoom-out crash in the photo gallery

app/src/main/java/com/seafile/seadroid2/cameraupload/CameraSyncAdapter.java, app/src/main/java/com/seafile/seadroid2/cameraupload/GalleryBucketUtils.java
Apparently, DATA column may be null in the media provider for videos. Not sure why, but this should avoid the crash.
[Due to lack of time, I only compile-tested this patch.]
=> fixes issue #491

app/src/main/java/com/seafile/seadroid2/ui/activity/BrowserActivity.java, app/src/main/res/values/strings.xml, build.gradle
Notify user duplicate file is about to upload, user can choose to cancel or proceed.
To check if the file already exist, cache it locally and compare its name before uploading.
=> Notify file already exist before uploading

app/src/main/java/com/seafile/seadroid2/data/DataManager.java, app/src/main/java/com/seafile/seadroid2/data/DatabaseHelper.java, app/src/main/java/com/seafile/seadroid2/util/Utils.java
* Don't store JSON content in SQL, instead write it out into files. They are now stored in the same place as the repo cache is already stored (.../Seafile/cache/dirent-$HASH.json).
* database layout change (DATABASE_VERSION++)
* Some trivial cleanup patches
fixes issue #475 where the JSON content of a directory was sufficiently large to trip up the sqlite database on Android.
Side notes:
* I think storing repo or dirent cache in External Storage, where other apps can read them, might a mistake. That data might be too private. A better place would be Context.getCacheDir(), where other apps have no access to.
* Another thought was regarding cache cleaning. Obviously any downloaded files should remain persistent as long as possible. But removing older thumbnails and repo/dirent cache file …
=> Fix: Move dirent JSON cache from SQLite to filesystem

app/src/main/java/com/seafile/seadroid2/ui/fragment/SettingsFragment.java, app/src/main/res/values-de/strings.xml, app/src/main/res/values/strings.xml
- The user can globally disable all sync in Android (via Settings -> Accounts -> Sync Automatically).
In that case, our camera upload will no longer work. To avoid user confusion, we should check for
that and gray out the camera upload entries in the SettingsFragment.
- Also add onResume() to refresh the fragment when necessary.
=> SettingsFragment: Disable camera upload when sync globally disabled

app/src/main/java/com/seafile/seadroid2/cameraupload/CameraSyncAdapter.java
Camera Upload tries to avoid creating duplicates when uploading files.
Previously, only the exact file name was checked for existence on the server.
This failed in situations where the file was already existing under a
duplicate name, like "DSC0001 (1).jpg".
This patch addresses that by using a regex to compare the filenames.
This fixes issue #503
=> Camera Upload: improve check for existing files

app/src/main/java/com/seafile/seadroid2/SeafConnection.java
fix #463
1.Incorrect url
`POST /seahub/api2/repos/4511bfaa-96ab-481f-8d04-6b19c4756f96/fileops/copy/?p=/escape/A%20&%20B HTTP/1.`
2. Correct one
`POST /seahub/api2/repos/4511bfaa-96ab-481f-8d04-6b19c4756f96/fileops/copy/?p=%2Fescape%2FA%20%26%20B HTTP/1.1`
=> Escape path param for creating, copying, moving, and deleting files and dirs

app/src/main/java/com/seafile/seadroid2/SeadroidApplication.java, app/src/main/java/com/seafile/seadroid2/SeafConnection.java, app/src/main/java/com/seafile/seadroid2/SettingsManager.java, app/src/main/java/com/seafile/seadroid2/cameraupload/CameraSyncAdapter.java, app/src/main/java/com/seafile/seadroid2/cameraupload/GalleryBucketUtils.java, app/src/main/java/com/seafile/seadroid2/data/DataManager.java, app/src/main/java/com/seafile/seadroid2/data/DatabaseHelper.java, app/src/main/java/com/seafile/seadroid2/data/StorageManager.java, app/src/main/java/com/seafile/seadroid2/data/StorageManagerGingerbread.java, app/src/main/java/com/seafile/seadroid2/data/StorageManagerKitKat.java, app/src/main/java/com/seafile/seadroid2/data/StorageManagerLollipop.java, app/src/main/java/com/seafile/seadroid2/gallery/ImageLoader.java, app/src/main/java/com/seafile/seadroid2/monitor/AutoUpdateManager.java, app/src/main/java/com/seafile/seadroid2/monitor/FileMonitorService.java, app/src/main/java/com/seafile/seadroid2/provider/SeafileProvider.java, app/src/main/java/com/seafile/seadroid2/ssl/CertsManager.java, app/src/main/java/com/seafile/seadroid2/ui/activity/BrowserActivity.java, app/src/main/java/com/seafile/seadroid2/ui/activity/ShareToSeafileActivity.java, app/src/main/java/com/seafile/seadroid2/ui/dialog/ClearCacheTaskDialog.java, app/src/main/java/com/seafile/seadroid2/ui/dialog/SwitchStorageTaskDialog.java, app/src/main/java/com/seafile/seadroid2/ui/dialog/TaskDialog.java, app/src/main/java/com/seafile/seadroid2/ui/fragment/SettingsFragment.java, app/src/main/java/com/seafile/seadroid2/util/ConcurrentAsyncTask.java, app/src/main/java/com/seafile/seadroid2/util/Utils.java, app/src/main/res/layout/bg_settings_section_cache.xml, app/src/main/res/layout/dialog_switch_storage.xml, app/src/main/res/values-de/strings.xml, app/src/main/res/values/strings.xml, app/src/main/res/xml/settings.xml
There are currently two methods to use an SD card with Seadroid (on some devices):
* On Android 6.0, you can "adopt" an SD card for all data storage.
* Older devices placed all app data ("External Storage") on the external SD card by design (don't know if this still done today on any device, but the Android framework still allows it)
This patchset adds a third option. It allows Seadroid to use an SD card on any device running Android 4.4 or newer. It adds an option to the Seadroid settings menu to select the storage location. On upgrade from 2.0.5, the internal storage will continue to be used. On fresh installs, the location with the most free space is selected.
This addresses issue #484 . Please see the individual patches for more details. Patch 3/3 is optional.
I've tested this …
=> Storage: Add option to move cache to external SD card on Android 4.4+

app/src/main/java/com/seafile/seadroid2/provider/SeafileProvider.java
under rare circumstances the seadroid cache might be empty.
=> SeafileProvider: fix possible NPE

app/src/main/java/com/seafile/seadroid2/data/StorageManager.java
Crash log
```
E/AndroidRuntime(21874): Process: com.seafile.seadroid2.debug, PID: 21874
E/AndroidRuntime(21874): java.lang.RuntimeException: An error occured while executing doInBackground()
E/AndroidRuntime(21874): 	at android.os.AsyncTask$3.done(AsyncTask.java:304)
E/AndroidRuntime(21874): 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
E/AndroidRuntime(21874): 	at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
E/AndroidRuntime(21874): 	at java.util.concurrent.FutureTask.run(FutureTask.java:242)
E/AndroidRuntime(21874): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
E/AndroidRuntime(21874): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
E/AndroidRuntime(21874): 	at …
```
=> Fix illegal argument exception when resuming Settings page after cleared caches

app/src/main/java/com/seafile/seadroid2/SettingsManager.java, app/src/main/java/com/seafile/seadroid2/data/ServerInfo.java, app/src/main/java/com/seafile/seadroid2/ui/fragment/SettingsFragment.java, app/src/main/res/xml/settings.xml
Only server version 5.1+ supports APIs for client side encryption under encrypted libraries, so hide the option for those running on pre 5.1 servers for a better ux.
fix #537
=> Hide client side encryption option if server not supported

app/src/main/java/com/seafile/seadroid2/crypto/Crypto.java, app/src/main/java/com/seafile/seadroid2/data/DataManager.java
Note that, the size of the buffer array remains constant. But if the buffer cannot be filled, like when it reaches the end of the file, we should only read and process the valid part. 
This patch uses offset to fix that.
=> Fix last file chunk might be filled with empty content bug

app/src/main/java/com/seafile/seadroid2/ui/activity/BrowserActivity.java
upload photos in encrypted blocks if client-side-encryption-settings was turned on under where is an encrypted repo.
=> Fix upload photos taken by camera under enc repos failed bug

app/src/main/res/values-ru/strings.xml
'Desc' was translated like 'description' that is not right.
Replaced with correct translations meaning descending sorting order.
=> Fix russian translation for 'desc'

app/src/main/java/com/seafile/seadroid2/ui/fragment/ReposFragment.java
So far pull-to-refresh hits the local caches for repos, dirs and files, missing
current changes on the server.
This commit `forceRefresh`es the view so the server is hit and changes induced
by other clients are synced.
Fixes haiwen/seadroid#558.
=> Make explicit manual refreshs hit the server

app/src/main/java/com/seafile/seadroid2/SeafConnection.java, app/src/main/java/com/seafile/seadroid2/data/DataManager.java, app/src/main/java/com/seafile/seadroid2/transfer/DownloadTask.java, app/src/main/java/com/seafile/seadroid2/transfer/DownloadTaskManager.java, app/src/main/java/com/seafile/seadroid2/transfer/TransferService.java, app/src/main/java/com/seafile/seadroid2/ui/activity/BrowserActivity.java, app/src/main/java/com/seafile/seadroid2/ui/fragment/ActivitiesFragment.java, app/src/main/java/com/seafile/seadroid2/util/Utils.java
When calculating blocks downloading progress, use pre known file size instead of summing it up block by block. This should fix the download progress inaccurate bug.
=> Fix blocks download progress inaccurate bug

app/src/main/java/com/seafile/seadroid2/ui/fragment/ReposFragment.java
In order to make downloading animation looks smooth, the indeterminateDuration of the progressbar should be the same value with system default. So set `indeterminateDuration` to be 3500 milliseconds.
https://github.com/android/platform_frameworks_base/blob/master/core/res/res/values/attrs.xml#L3966
https://github.com/android/platform_frameworks_base/blob/master/core/res/res/values/styles.xml#L398
=> Fix progress indeterminateDuration integer inconsistent bug

app/src/main/java/com/seafile/seadroid2/SeafConnection.java, app/src/test/java/com/seafile/seadroid2/util/UtilsTest.java
The bug is `req.contentLength` will return -1 when downloading large (e.g. 2.6GB) file.
This patch should fix #570
=> Fix bizarre percentage when downloading large files

app/src/main/java/com/seafile/seadroid2/ui/activity/AccountsActivity.java, app/src/main/java/com/seafile/seadroid2/ui/activity/CreateGesturePasswordActivity.java, app/src/main/java/com/seafile/seadroid2/ui/activity/UnlockGesturePasswordActivity.java, app/src/main/java/com/seafile/seadroid2/ui/fragment/SettingsFragment.java
We found some bugs in your android app and decided to fix it:
1 - Back button was always enabled when there was no current account defined which led to the destruction of the current activity, creation of new browser activty and then creation of new accounts activity
2 - Gesture lock switch preference was staying on even when there was no gesture pattern defined
3 - Back button in gesture lock activity was letting users retry the gesture pattern more than 5 times without waiting 30 seconds
=> Bug fixing

app/src/main/java/com/seafile/seadroid2/ssl/SSLTrustManager.java
If supplied certificate chain is invalid, this may result in an infinite
loop.
Example problem: additional server certificate.
Update for #575 as requested.
=> Fix infinite loop for invalid cert chain

app/build.gradle
I have an issue with the app crashing when I try to access context menu of any file/folder or library. Using newer version of the BottomSheet dependency fixes the problem. Tested on emulated Nexus 5X with Android 7.0 and 8.0 and on physical device Nexus 5X with android 8.0
=> Use new version of BottomSheet, fixes issue #713

app/src/main/AndroidManifest.xml, app/src/main/res/xml/network_security_config.xml
This allows user added CAs to work with Seadroid, letting users (among other things) establish a secure channel for local domains (impossible without this change). 
Exact same changes as in [nextcloud/android@727375642d4357486ce0fd3f4f4f2a80999f34fa](https://github.com/nextcloud/android/commit/727375642d4357486ce0fd3f4f4f2a80999f34fa)
Discussion thread: [[BUG] Valid personal certificate detected as invalid on seadroid](https://forum.seafile.com/t/bug-valid-personal-certificate-detected-as-invalid-on-seadroid/6373)
=> Allow user added CAs

.travis.yml
```
A problem occurred configuring project ':app'.
> Failed to install the following Android SDK packages as some licences have not been accepted.
build-tools;28.0.3 Android SDK Build-Tools 28.0.3
```
This issue might come from Travis because we are not using Build-Tools version '28.0.3' but '27.0.3'
I read a workaround on the travis community:
https://travis-ci.community/t/accept-license-for-android-build-tools-27-0-3-bug/549
=> Fixed travis pipeline

app/src/main/java/com/seafile/seadroid2/cameraupload/GalleryBucketUtils.java
Fixes #874
Fixes #893 
cursor.getString returning a null name caused the application to crash in the hashCode override function:
```
E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.hashCode()' on a null object reference
E AndroidRuntime: 	at com.seafile.seadroid2.cameraupload.GalleryBucketUtils$Bucket.hashCode(GalleryBucketUtils.java:51)
```
Reproduced and fix tested on Android 11.
Maybe more null checks should be added as defense in depth against different framework implementations, but I did not want to modify the existing logic more than necessary for my test to work.
=> Do not use GalleryBucket if name is null

app/src/main/java/com/seafile/seadroid2/ssl/SSLSeafileSocketFactory.java
Following from #903. TLDR: ChaCha20 is much faster for devices that do not provide hardware AES acceleration (eg. Raspberry Pi 4), and secure to the point of being included in TLS1.3. [The Mozilla Wiki provides a list](https://wiki.mozilla.org/Security/Server_Side_TLS#Intermediate_compatibility_.28recommended.29) of secure cipher suites, and the ones added here are listed there as secure.
=> Add CHACHA20_POLY1305 to the ssl cipher list

.travis.yml
Travis was broken because of this:
``` 
Checking the license for package Android SDK Build-Tools 29.0.2 in /usr/local/android-sdk/licenses
Warning: License for package Android SDK Build-Tools 29.0.2 not accepted.
Checking the license for package Android SDK Platform 29 in /usr/local/android-sdk/licenses
Warning: License for package Android SDK Platform 29 not accepted.
FAILURE: Build failed with an exception
```
=> Fix travis pipeline

app/src/main/java/com/seafile/seadroid2/account/ui/SingleSignOnAuthorizeActivity.java
This PR is very similar to haiwen/seafile-iOS#356 which would fix `Error 403: disallowed_useragent` when using Google OAUTH2 for Single Sign-On.
The system's user-agent is used before requesting the page which solves this problem.
This also fixes #783.
=> Fix "disallowed_useragent" Error when using Google OAUTH2 SSO

app/src/main/java/com/seafile/seadroid2/util/Utils.java
I've added `adoc` and `asciidoc` to be file extension that cause the plain text editor to open.
This would be really convenient to view and edit asciidoc files on mobile.
=> Added asciidoc file extensions to open with plain text editor
