haiwen/seadroid

src/com/seafile/seadroid2/ui/CustomClearableEditText.java
This pull request fixes the password exposure of certain keyboards.
=> Fix password exposure on some keyboards. Fixes #224.

src/com/seafile/seadroid2/ui/fragment/ReposFragment.java, src/com/seafile/seadroid2/ui/fragment/StarredFragment.java
fix the loadAnimation null pointer exception
error log
```
at android.view.animation.AnimationUtils.loadAnimation(AnimationUtils.java:71)
at com.seafile.seadroid2.ui.fragment.ReposFragment.showLoading(ReposFragment.java:535)
at com.seafile.seadroid2.ui.fragment.ReposFragment.access$200(ReposFragment.java:42)
at com.seafile.seadroid2.ui.fragment.ReposFragment$LoadDirTask.onPostExecute(ReposFragment.java:616)
at com.seafile.seadroid2.ui.fragment.ReposFragment$LoadDirTask.onPostExecute(ReposFragment.java:545)
```
=> load animation null pointer

src/com/seafile/seadroid2/ui/activity/UnlockGesturePasswordActivity.java
fix Gesture lock is trivial to bypass by pressing the 'back' button twice quickly #219
=> override back button default behavior

res/values/strings.xml
fix A question about the meaning of a string... #232 
I have changed the translation of the default language, hope other contributors from Transifex can notice the change and update translations of each language resource respectively.
=> fix string ambiguity

src/com/seafile/seadroid2/cameraupload/CameraUploadService.java
stop uploading if mobile upload perference is disabled but only mobile network is available
=> mobile network camera upload

src/com/seafile/seadroid2/avatar/AvatarDBHelper.java, src/com/seafile/seadroid2/ui/activity/AccountsActivity.java, src/com/seafile/seadroid2/ui/adapter/AccountAdapter.java
1. fix off by one bug when querying database
2. drop 1 second delay when loading new avatar.
=> drop loading avatar animations

src/com/seafile/seadroid2/ui/activity/AccountsActivity.java
fix force exit when all accounts info deleted #230
=> force exit when current account was deleted

src/com/seafile/seadroid2/account/Account.java, src/com/seafile/seadroid2/account/AccountInfo.java, src/com/seafile/seadroid2/ui/activity/SettingsActivity.java, src/com/seafile/seadroid2/ui/fragment/SettingsPreferenceFragment.java, src/com/seafile/seadroid2/util/Utils.java
the app crashed when trying to open settings menu if network down. To resolve this error, cached user info and show cache when offline.
Also show a progress bar at the top right corner of SettingsActivity when loading.
=> show cached user info when network down

res/layout/file_activity.xml, src/com/seafile/seadroid2/transfer/DownloadTaskManager.java, src/com/seafile/seadroid2/ui/activity/FileActivity.java
fix Opening files doesn't work properly #258
=> Open file progress refresh

res/layout-sw600dp/gesturepassword_create.xml, res/layout-sw600dp/gesturepassword_unlock.xml, res/layout/custom_ssl_confirm_title_view.xml, res/layout/dialog_ssl_confirm.xml, res/layout/gesturepassword_create.xml, res/layout/gesturepassword_unlock.xml, res/layout/seafile_dialog_layout.xml, res/layout/shibboleth_welcome_layout.xml, res/values/colors.xml, src/com/seafile/seadroid2/ui/dialog/UploadChoiceDialog.java
This PR provides the interfaces for theme customization.  
To change the theme, just simply modify several variables as described below.  
* theme color, go to `res/values/colors.xml`, set the wanted color value to `theme_color`  
* dialog color, go to `res/values/colors.xml`, set the wanted color value to `dialog_theme_color`
=> support custom theme styles

README.md
=> Update README: add more instructions to build APK

res/values/strings.xml, src/com/seafile/seadroid2/data/DataManager.java, src/com/seafile/seadroid2/fileschooser/MultiFileChooserActivity.java, src/com/seafile/seadroid2/gallery/MultipleImageSelectionActivity.java, src/com/seafile/seadroid2/ui/activity/UnlockGesturePasswordActivity.java, src/com/seafile/seadroid2/util/Utils.java
Thanks to "Fixed issue where space character wouldn't appear in last update time of a library" #262
=> Fixed space character issues

AndroidManifest.xml
allow browsing most Activities in Landscape perspective except `UnlockGesturePasswordActivity` and `CreateGesturePasswordActivity` because they will mess up if enabled.
=> support landscape view

src/com/seafile/seadroid2/ui/activity/BrowserActivity.java, src/com/seafile/seadroid2/ui/dialog/FetchFileDialog.java
changed to use timer to refresh download progress
=> fix export file not working bug

src/com/seafile/seadroid2/cameraupload/CameraUploadService.java, src/com/seafile/seadroid2/transfer/TransferManager.java
fix Camera Upload causes ANR #291
=> optimize camera upload service to avoid ANRs

src/com/seafile/seadroid2/data/DataManager.java
@forouher @lins05 the question mark "?" issue was fixed in the [new web API](https://github.com/haiwen/seafile-docs/blob/master/develop/web_api.md#get-thumbnail-image)
=> fix question mark issue

src/com/seafile/seadroid2/data/DataManager.java, src/com/seafile/seadroid2/data/DatabaseHelper.java, src/com/seafile/seadroid2/ui/fragment/StarredFragment.java
Probably not a very important feature inside the Seafile app.
However the SeafileProvider (next pull request) relies on it.
=> Cache StarredFiles

src/com/seafile/seadroid2/SeafConnection.java, src/com/seafile/seadroid2/SettingsManager.java, src/com/seafile/seadroid2/data/DataManager.java, src/com/seafile/seadroid2/data/ServerInfo.java, src/com/seafile/seadroid2/ui/activity/BrowserActivity.java
=> hide Activities-tab on non-pro edition server

src/com/seafile/seadroid2/ui/activity/BrowserActivity.java, src/com/seafile/seadroid2/util/Utils.java, src/com/seafile/seadroid2/util/UtilsJellyBean.java
As discussed in https://github.com/forouher/seadroid/pull/9
Put this into own pull request, as it technically has nothing to do with https://github.com/haiwen/seadroid/pull/287
=> File upload: allow to select multiple files

src/com/seafile/seadroid2/data/DataManager.java, src/com/seafile/seadroid2/data/SeafRepo.java
the try catch block doesn\`t work as expected if duplicate the try catch block in 'fromJson' method
=> catch parse repo exceptions

res/menu/browser_menu.xml, res/values/strings.xml, src/com/seafile/seadroid2/ui/NotificationUtils.java, src/com/seafile/seadroid2/ui/activity/BrowserActivity.java
* Allow recursive folder downloads
* Fix crashes occuring when
* downloading empty files
* opening a file causes a SecurityException due to the system choosing an inappropriate app
=> Recursive downloads + fix some crashes

src/com/seafile/seadroid2/SettingsManager.java, src/com/seafile/seadroid2/ui/fragment/SettingsPreferenceFragment.java
refactor code and methods in order to manage settings in an elegant way
=> refactor settings fragment

src/com/seafile/seadroid2/ui/activity/BrowserActivity.java
The assembled file path is incorrect,
Wrong path: Android_dev/gesture_lock
Correct path: Android_dev/screenshot/gesture_lock
=> fix download folder recursively error

src/com/seafile/seadroid2/notification/BaseNotificationProvider.java, src/com/seafile/seadroid2/notification/DownloadNotificationProvider.java, src/com/seafile/seadroid2/notification/UploadNotificationProvider.java, src/com/seafile/seadroid2/transfer/TransferService.java, src/com/seafile/seadroid2/ui/activity/BrowserActivity.java, src/com/seafile/seadroid2/ui/activity/FileActivity.java
1. hide notification when cancel download in FileActivity
2. calculate progress by transferService rather than by SeafDrients
3. show toast when download or upload files (revert commented toast)
=> Review notification

res/values/strings.xml, src/com/seafile/seadroid2/ui/activity/SeafilePathChooserActivity.java
1. remove duplicate  & unused strings
2. improve strings with complete meanings
=> review language resources

src/com/seafile/seadroid2/ui/activity/AccountDetailActivity.java
fix Whitespace after email address doesn't get stripped in new account setup #357
=> trim texts of server url and email address

src/com/seafile/seadroid2/account/AccountDBHelper.java
carefully update onUpgrade() when bumping database versions to make
sure user data is saved.
fix #365
=> upgrade database without losing user data

res/values/strings.xml, src/com/seafile/seadroid2/ui/activity/ShareToSeafileActivity.java
this patch should fix [Overwriting existing files while saving](https://forum.seafile-server.org/t/overwriting-existing-files-while-saving/1404)
=> support overwrite shared files from other App

src/com/seafile/seadroid2/ui/activity/GalleryActivity.java
fixed Image gallery jumps back to first image on screen rotate #373
=> restore gallery browsing progress of rotation

src/com/seafile/seadroid2/data/DataManager.java, src/com/seafile/seadroid2/ui/activity/SearchActivity.java
=> Restore search rlt when configuration changed

src/com/seafile/seadroid2/SettingsManager.java, src/com/seafile/seadroid2/data/SeafGroup.java, src/com/seafile/seadroid2/ui/activity/BrowserActivity.java, src/com/seafile/seadroid2/ui/adapter/SeafItemAdapter.java, src/com/seafile/seadroid2/ui/fragment/ReposFragment.java
=> refactor sort files logic

res/layout/list_item_single_choice.xml, src/com/seafile/seadroid2/ui/SeafileStyleDialogBuilder.java, src/com/seafile/seadroid2/ui/activity/BrowserActivity.java
=> optimize ui of sort files

src/com/seafile/seadroid2/ui/activity/GalleryActivity.java
sort photos in gallery based on global sorting type and order.
=> sort photos in gallery

src/com/seafile/seadroid2/ui/activity/BrowserActivity.java
=> enable Download folder menu inside of read-only repo

src/com/seafile/seadroid2/data/DataManager.java, src/com/seafile/seadroid2/ui/WidgetUtils.java, src/com/seafile/seadroid2/ui/activity/BrowserActivity.java, src/com/seafile/seadroid2/ui/activity/FileActivity.java, src/com/seafile/seadroid2/ui/activity/GalleryActivity.java, src/com/seafile/seadroid2/ui/activity/SearchActivity.java, src/com/seafile/seadroid2/ui/fragment/ReposFragment.java
=> support view starred & searched pics in gallery

README.md, THIRD_PARTY_LICENSE.md, pom.xml, res/layout/tabs_main.xml, res/layout/transfer_list_layout.xml, src/com/seafile/seadroid2/ui/activity/BrowserActivity.java, src/com/seafile/seadroid2/ui/activity/TransferActivity.java
same with improve UI style of TabBar #392
Thanks [astuetz](https://github.com/astuetz) for his [PagerSlidingTabStrip](https://github.com/astuetz/PagerSlidingTabStrip)
=> support interactive indicator for viewpager

src/com/seafile/seadroid2/ui/activity/BrowserActivity.java
Fixed restore state of previous browsing #412
=> fix several bugs for releasing v1.9.1

res/layout-sw600dp/list_item_entry.xml, res/layout-xlarge/list_item_entry.xml, res/layout/list_item_entry.xml
layout testing has passed on both Nexus 7 (layout for tablets) and Nexus 6 (layout for phones) devices.
=> update list_item_entry.xml to fix layout mess up

src/com/seafile/seadroid2/ui/activity/ShareToSeafileActivity.java
fixed Upload via Share intent #406
=> support upload files shared from cloud drives

src/com/seafile/seadroid2/ui/WidgetUtils.java, src/com/seafile/seadroid2/ui/activity/BrowserActivity.java, src/com/seafile/seadroid2/ui/activity/FileActivity.java, src/com/seafile/seadroid2/ui/activity/SearchActivity.java, src/com/seafile/seadroid2/ui/dialog/OpenAsDialog.java, src/com/seafile/seadroid2/ui/fragment/ActivitiesFragment.java
=> A couple of fixes regarding opening files with undeterminable mime types.

src/com/seafile/seadroid2/ui/activity/GalleryActivity.java
=> fixed IndexOutOfBoundsException when accessing list

src/com/seafile/seadroid2/ui/fragment/ReposFragment.java
=> Fixed crash when long-pressing a library

res/layout/starred_fragment.xml, res/layout/starred_list_item.xml, res/values/strings.xml, src/com/seafile/seadroid2/SeafConnection.java, src/com/seafile/seadroid2/data/DataManager.java, src/com/seafile/seadroid2/ui/activity/BrowserActivity.java, src/com/seafile/seadroid2/ui/adapter/StarredItemAdapter.java, src/com/seafile/seadroid2/ui/fragment/StarredFragment.java
support unstar multiple files in STARRED tab
related to #385 #256
=> Support unstar a file

res/layout/dialog_copy_move_file.xml, res/values/strings.xml, src/com/seafile/seadroid2/ui/activity/BrowserActivity.java, src/com/seafile/seadroid2/ui/dialog/CopyMoveDialog.java, src/com/seafile/seadroid2/util/Utils.java
Also display summary infos when processing multiple files in dialog
=> Set dialog not cancellable when editing multiple files

app/src/main/java/com/seafile/seadroid2/ui/fragment/ActivitiesFragment.java
=> Fix Android app activity tab #448

app/src/main/java/com/seafile/seadroid2/ui/CustomClearableEditText.java, app/src/main/java/com/seafile/seadroid2/ui/activity/AccountDetailActivity.java, app/src/main/java/com/seafile/seadroid2/util/Utils.java, app/src/main/res/layout/clearable_edit_text.xml, app/src/main/res/values/strings.xml
Web api for [Check Account Info](https://github.com/haiwen/seafile-docs/blob/master/develop/web_api.md#check-account-info)
=> Support login by username or email address

app/build.gradle, app/src/test/java/com/seafile/seadroid2/util/UtilsTest.java
- junit tests belong to app/src/test/java/...
- add gradle dependencies
- add missing dependency in test file
Now the unit test can be run from within Android Studio. :)
Btw: Would you guys be interested in PRs that add unit tests for existing/new features?
=> gradle: fix unit test dependencies

app/src/main/java/com/seafile/seadroid2/cameraupload/GalleryBucketUtils.java
Had an NPE under unusual circumstances (no sdcard present) in the emulator.
Not sure if it can actually happen in the real world.
But just to be sure...
=> Camera Upload: fix potential NPE

app/src/main/java/com/seafile/seadroid2/account/ui/ShibbolethActivity.java, app/src/main/java/com/seafile/seadroid2/account/ui/ShibbolethAuthorizeActivity.java, app/src/main/java/com/seafile/seadroid2/ui/dialog/SslConfirmDialog.java, app/src/main/java/com/seafile/seadroid2/ui/fragment/ActivitiesFragment.java, app/src/main/java/com/seafile/seadroid2/util/Utils.java
=> Fix Shibboleth account creation not working since 2.0.0 #488

app/src/main/java/com/seafile/seadroid2/cameraupload/GalleryBucketUtils.java
=> fix another NPE related to #491

app/src/main/java/com/seafile/seadroid2/account/ui/AccountDetailActivity.java, app/src/main/java/com/seafile/seadroid2/ui/EmailAutoCompleteTextView.java, app/src/main/res/layout/account_detail.xml
Show a floating label when the hint is hidden due to the user inputting text
=> Show a floating label when the hint is hidden

app/src/main/java/com/seafile/seadroid2/account/ui/SeafileAuthenticatorActivity.java
Have currently no dev environment. Would be great if you could check it and either merge or apply a fix and close this PR.
=> Fix app.seafile.de Server URL

app/src/main/res/values-fr/strings.xml
=> Fix typo for french translation

app/src/main/java/com/seafile/seadroid2/transfer/DownloadTask.java, app/src/main/java/com/seafile/seadroid2/ui/activity/BrowserActivity.java
=> Fix multi files download failed bug in enc repos

app/src/main/java/com/seafile/seadroid2/SettingsManager.java, app/src/main/java/com/seafile/seadroid2/data/DataManager.java, app/src/main/java/com/seafile/seadroid2/data/DatabaseHelper.java, app/src/main/java/com/seafile/seadroid2/ui/dialog/ClearPasswordTaskDialog.java, app/src/main/java/com/seafile/seadroid2/ui/fragment/SettingsFragment.java, app/src/main/res/layout/dialog_delete_password.xml, app/src/main/res/values/strings.xml, app/src/main/res/xml/settings.xml
Popup a window to ask if user wants to clear passwords.
=> Support clear passwords of encrypted repos

app/src/main/java/com/seafile/seadroid2/SeafConnection.java, app/src/main/java/com/seafile/seadroid2/data/Block.java, app/src/main/java/com/seafile/seadroid2/data/DataManager.java, app/src/main/java/com/seafile/seadroid2/data/FileBlocks.java, app/src/main/java/com/seafile/seadroid2/data/SeafRepo.java, app/src/main/java/com/seafile/seadroid2/provider/SeafileProvider.java, app/src/main/java/com/seafile/seadroid2/transfer/UploadTask.java
=> Fix several review issues for #487

app/src/main/java/com/seafile/seadroid2/SeadroidApplication.java, app/src/main/java/com/seafile/seadroid2/SeafConnection.java, app/src/main/java/com/seafile/seadroid2/SettingsManager.java, app/src/main/java/com/seafile/seadroid2/crypto/Crypto.java, app/src/main/java/com/seafile/seadroid2/monitor/FileMonitorService.java, app/src/main/java/com/seafile/seadroid2/ui/fragment/SettingsFragment.java, app/src/main/res/values-es-rAR/strings.xml, app/src/main/res/values-es/strings.xml, app/src/main/res/values-ja-rJP/strings.xml, app/src/main/res/values-ko/strings.xml, app/src/main/res/values-pl-rPL/strings.xml, app/src/main/res/values-ru/strings.xml, app/src/main/res/values-zh-rCN/strings.xml, app/src/main/res/values/strings.xml, app/src/main/res/xml/settings.xml
1. Support auto clear passwords when logout account
2. Update i18n
3. Fix an ssl certificate not trusted error
4. Fix several operation bugs
=> Fix several reviewed issues for 2.1.0 preview version

app/build.gradle, app/src/main/java/com/seafile/seadroid2/ui/activity/BrowserActivity.java, app/src/main/java/com/seafile/seadroid2/ui/dialog/SortFilesDialogFragment.java, build.gradle
Code clean up and refactor according to offical design patterns
=> Code clean up

app/src/main/java/com/seafile/seadroid2/ui/dialog/NewDirDialog.java, app/src/main/java/com/seafile/seadroid2/ui/dialog/NewFileDialog.java, app/src/main/java/com/seafile/seadroid2/ui/dialog/PasswordDialog.java, app/src/main/java/com/seafile/seadroid2/ui/dialog/RenameFileDialog.java
Fix Display keybord if password input is required #538
=> Display soft keyboard if text input is required in dialog

app/src/main/java/com/seafile/seadroid2/data/DataManager.java, app/src/main/java/com/seafile/seadroid2/data/FileBlocks.java
Fix crash when downloading empty files under encrypted repo
#537
=> Fix crash when downloading empty files under encrypted repo

app/src/main/java/com/seafile/seadroid2/monitor/AutoUpdateInfo.java, app/src/main/java/com/seafile/seadroid2/monitor/AutoUpdateManager.java, app/src/main/java/com/seafile/seadroid2/monitor/CachedFileChangedListener.java, app/src/main/java/com/seafile/seadroid2/monitor/FileMonitorService.java, app/src/main/java/com/seafile/seadroid2/monitor/MonitorDBHelper.java, app/src/main/java/com/seafile/seadroid2/monitor/SeafileObserver.java, app/src/main/java/com/seafile/seadroid2/transfer/DownloadTask.java, app/src/main/java/com/seafile/seadroid2/transfer/DownloadTaskInfo.java, app/src/main/java/com/seafile/seadroid2/transfer/UploadTask.java, app/src/main/java/com/seafile/seadroid2/transfer/UploadTaskInfo.java
=> Support auto update files under encrypted repo

app/src/main/java/com/seafile/seadroid2/ui/activity/BrowserActivity.java, app/src/main/java/com/seafile/seadroid2/ui/fragment/ReposFragment.java
[Maintain/Save/Restore scroll position when returning to a ListView](http://stackoverflow.com/questions/3014089/maintain-save-restore-scroll-position-when-returning-to-a-listview/3035521#3035521)
fix #522
=> Restore scroll position when browsing between folder and subfolders

app/src/main/res/layout/dialog_open_file.xml, app/src/main/res/layout/transfer_list_item.xml
releated to 7f76d09864fa06741f2fe252a44b849e3b69a384
=> Style the horizontal progressbar in material theme

app/src/main/java/com/seafile/seadroid2/ui/activity/BrowserActivity.java, app/src/main/java/com/seafile/seadroid2/ui/fragment/ReposFragment.java
=> Fix starred file under encrypted repo still accessible bug

app/src/main/java/com/seafile/seadroid2/data/DatabaseHelper.java, app/src/main/java/com/seafile/seadroid2/ui/activity/SeafilePathChooserActivity.java, app/src/main/java/com/seafile/seadroid2/ui/activity/ShareToSeafileActivity.java
this should fix #550 
interesting reference [Android Memory Leak](http://stevevallay.github.io/blog/2014/11/17/memory-leak/)
=> Fix crash when sharing file from other app

app/src/main/java/com/seafile/seadroid2/ui/fragment/ActivitiesFragment.java
Fix some click event ignored bug when client side decrypt enabled
=> Fix click activity item not response bug

app/src/main/java/com/seafile/seadroid2/SeafConnection.java, app/src/main/java/com/seafile/seadroid2/SeafException.java, app/src/main/java/com/seafile/seadroid2/account/ui/AccountDetailActivity.java, app/src/main/res/layout/account_detail.xml, app/src/main/res/values/strings.xml
1. In Seahub, go to Settings -> Two-factor Authentication -> enable Two-Factor Authentication
2. logout the app
3. login as usual, and the authentication token input box will show up
4. input auth token and relogin
5. done
Open the two-factor authentication app, e.g.Google Authenticator, on your device to view your authentication token and verify your identify.
=> Support two-factor authentication

app/src/main/java/com/seafile/seadroid2/ui/activity/BrowserActivity.java, app/src/main/java/com/seafile/seadroid2/ui/fragment/ActivitiesFragment.java
When click one item of activity list, if the item type is dir, then
1. switch tab to LIBRARY
2. nav into the repo/path directory
=> Fix several bugs when open files (folders) in activity list

app/src/main/java/com/seafile/seadroid2/cameraupload/CloudLibrarySelectionFragment.java, app/src/main/java/com/seafile/seadroid2/crypto/Crypto.java, app/src/main/java/com/seafile/seadroid2/data/DataManager.java, app/src/main/java/com/seafile/seadroid2/transfer/DownloadTask.java, app/src/main/java/com/seafile/seadroid2/transfer/DownloadTaskManager.java, app/src/main/java/com/seafile/seadroid2/transfer/TransferService.java, app/src/main/java/com/seafile/seadroid2/ui/activity/BrowserActivity.java, app/src/main/java/com/seafile/seadroid2/ui/activity/FileActivity.java, app/src/main/java/com/seafile/seadroid2/ui/activity/SeafilePathChooserActivity.java, app/src/main/java/com/seafile/seadroid2/ui/adapter/GalleryAdapter.java, app/src/main/java/com/seafile/seadroid2/ui/dialog/PasswordDialog.java, app/src/main/java/com/seafile/seadroid2/ui/fragment/ActivitiesFragment.java, app/src/main/java/com/seafile/seadroid2/ui/fragment/ReposFragment.java
[As discussed](https://github.com/haiwen/seadroid/pull/487#discussion_r64400728), there is a lot of code duplication thoughout the patch #487.
This patch deleted the duplicate code and refactored some methods.
=> [Refactor] Remove duplicate code

app/src/main/java/com/seafile/seadroid2/ui/activity/BrowserActivity.java
Fix file list not auto refresh bug after a file was successfully uploaded.
#563 
the bug was introduced by e44a97ea6e33ec5615ab4a71c91f574b420512a3
=> Fix file list not auto refresh bug

app/build.gradle, app/src/main/AndroidManifest.xml, app/src/main/res/menu-sw480dp/browser_menu.xml
fix NullPointerException when attempt to invoke interface method 'android.view.MenuItem android.view.MenuItem.setVisible(boolean)'.
=> Fix NPE bug when rendering menuCreateRepo

app/src/main/res/layout/list_item_authenticator.xml
Issues only occurs before API level 17
=> Fix layout issues when choosing a Seafile server

app/src/main/java/com/seafile/seadroid2/ui/activity/ShareToSeafileActivity.java
Fix screen total blank bug when external share cancelled for a better ux
=> Fix screen total blank bug when external share cancelled

app/src/main/java/com/seafile/seadroid2/ui/activity/AccountsActivity.java
The issues is, users can never return back to home screen by clicking back button after deleted or logged current account. This patch should fix the bug.
Return to home screen when
* no accounts added
* current account was deleted
* current account was logged out
=> Fix return home screen failed bug when back button preesed

app/build.gradle, app/src/main/java/com/seafile/seadroid2/ui/adapter/SeafItemAdapter.java, app/src/main/java/com/seafile/seadroid2/ui/fragment/ReposFragment.java, build.gradle
1、fix root folder permission 
2、fix bug for title  back  button  was  not  show
=> fix root folder permission 

app/src/main/res/values-zh-rTW/strings.xml
=> Updated i18n for chinese transition words

app/src/main/java/com/seafile/seadroid2/SeafConnection.java
Fix regression introduced in a4d2a026.
=> Make detection of invalidated token work again

app/build.gradle, app/src/main/res/values/attrs.xml, build.gradle, gradle/wrapper/gradle-wrapper.properties
fix code run in android studio error
=> fix code run in android studio error

app/src/main/res/layout/list_item_entry.xml, app/src/main/res/values/colors.xml, app/src/main/res/values/dimens.xml
=> changed repo list ui

app/src/main/res/layout/repos_fragment.xml
Make scrolling in huge libraries easier, closes #681
=> enable fast scroll

app/build.gradle, app/src/main/java/com/seafile/seadroid2/SeafConnection.java, app/src/main/java/com/seafile/seadroid2/data/DataManager.java, app/src/main/java/com/seafile/seadroid2/httputils/NoSSLv3Factory.java, app/src/main/java/com/seafile/seadroid2/httputils/RequestManager.java, app/src/main/java/com/seafile/seadroid2/provider/SeafileProvider.java, app/src/main/java/com/seafile/seadroid2/ui/activity/BrowserActivity.java, app/src/main/java/com/seafile/seadroid2/util/UriFilePath.java
fix crash when upload large file
=> replace upload file network libs

app/build.gradle, app/src/main/java/com/seafile/seadroid2/SeafConnection.java, build.gradle, gradle/wrapper/gradle-wrapper.properties
update gradle build version
update version name
=> fix upload file failed in root dir

.travis.yml, app/build.gradle, build.gradle
See https://travis-ci.org/shoeper/seadroid
fixes https://github.com/haiwen/seadroid/issues/741
=> fix build & ci

app/build.gradle
=> Share display notification bar

app/build.gradle, app/src/main/java/com/seafile/seadroid2/transfer/UploadTaskManager.java, app/src/main/java/com/seafile/seadroid2/ui/activity/ShareToSeafileActivity.java
Hide image upload notification progress
=> Hide image upload notification

app/build.gradle, app/src/main/java/com/seafile/seadroid2/SettingsManager.java, app/src/main/java/com/seafile/seadroid2/account/Account.java, app/src/main/java/com/seafile/seadroid2/account/AccountDBHelper.java, app/src/main/java/com/seafile/seadroid2/account/AccountInfo.java, app/src/main/java/com/seafile/seadroid2/account/AccountManager.java, app/src/main/java/com/seafile/seadroid2/account/Authenticator.java, app/src/main/java/com/seafile/seadroid2/account/ui/AccountDetailActivity.java, app/src/main/java/com/seafile/seadroid2/account/ui/SeafileAuthenticatorActivity.java, app/src/main/java/com/seafile/seadroid2/account/ui/SingleSignOnAuthorizeActivity.java, app/src/main/java/com/seafile/seadroid2/ui/activity/AccountsActivity.java, app/src/main/java/com/seafile/seadroid2/ui/adapter/AccountAdapter.java, app/src/main/java/com/seafile/seadroid2/util/Utils.java
=> Account display updated

app/build.gradle, app/src/main/java/com/seafile/seadroid2/account/Account.java, app/src/main/java/com/seafile/seadroid2/account/AccountDBHelper.java, app/src/main/java/com/seafile/seadroid2/account/ui/SeafileAuthenticatorActivity.java, app/src/main/java/com/seafile/seadroid2/cameraupload/CameraUploadConfigActivity.java, app/src/main/java/com/seafile/seadroid2/ui/activity/AccountsActivity.java, app/src/main/java/com/seafile/seadroid2/util/SystemSwitchUtils.java, app/src/main/java/com/seafile/seadroid2/util/Utils.java
Account display updated and Open the synchronization
=> Account display updated and Open the synchronization

app/src/main/java/com/seafile/seadroid2/account/ui/SingleSignOnAuthorizeActivity.java
signlogin certificate past due
=> signlogin certificate expiration

app/build.gradle, app/src/main/java/com/seafile/seadroid2/data/SeafPhoto.java, app/src/main/java/com/seafile/seadroid2/ui/activity/GalleryActivity.java, app/src/main/java/com/seafile/seadroid2/ui/adapter/GalleryAdapter.java, app/src/main/java/com/seafile/seadroid2/util/Utils.java, app/src/main/res/layout/gallery_activity_layout.xml, app/src/main/res/layout/gallery_view_item.xml, app/src/main/res/values/dimens.xml
=> Displays big image

app/build.gradle, build.gradle
=> revise a targetSdkVersion

app/build.gradle
=> addplay64-bit

app/build.gradle, app/src/main/AndroidManifest.xml
android 9.0 foreground_service
=> foreground_service

app/build.gradle, app/src/main/res/values-de/strings.xml, app/src/main/res/values-es-rAR/strings.xml, app/src/main/res/values-es/strings.xml, app/src/main/res/values-fr/strings.xml, app/src/main/res/values-ja-rJP/strings.xml, app/src/main/res/values-ko/strings.xml, app/src/main/res/values-ru/strings.xml, app/src/main/res/values-zh-rCN/strings.xml
=> TranslationVersion

app/build.gradle, app/src/main/java/com/seafile/seadroid2/SeafConnection.java, app/src/main/java/com/seafile/seadroid2/util/Utils.java
=> ServerUpdate

app/build.gradle, app/src/main/java/com/seafile/seadroid2/util/Utils.java
Text opens an extension of the file format
=> addfileformat

app/build.gradle, app/src/main/java/com/seafile/seadroid2/util/Utils.java
=> addFileMime

app/build.gradle, app/src/main/AndroidManifest.xml, app/src/main/java/com/seafile/seadroid2/ui/WidgetUtils.java, app/src/main/java/com/seafile/seadroid2/ui/activity/BrowserActivity.java, app/src/main/java/com/seafile/seadroid2/ui/activity/MarkdownActivity.java, build.gradle
=> TreeDocumentFile

app/build.gradle, app/src/main/java/com/seafile/seadroid2/ui/activity/SeafilePathChooserActivity.java, app/src/main/java/com/seafile/seadroid2/ui/dialog/NewDirDialog.java, app/src/main/res/layout/seafile_path_chooser.xml
"new folder" option missing when sharing via other app
=> shareSaveFile

app/build.gradle, app/src/main/java/com/seafile/seadroid2/ui/adapter/GalleryAdapter.java
=> addLoading

app/src/main/java/com/seafile/seadroid2/ui/activity/SeafilePathChooserActivity.java, app/src/main/res/layout/seafile_path_chooser.xml
=> hide newfolder 

app/build.gradle, app/src/main/java/com/seafile/seadroid2/SeadroidApplication.java, app/src/main/java/com/seafile/seadroid2/cameraupload/BucketsSelectionFragment.java, app/src/main/java/com/seafile/seadroid2/cameraupload/CameraSyncAdapter.java, app/src/main/java/com/seafile/seadroid2/cameraupload/CameraUploadConfigActivity.java, app/src/main/java/com/seafile/seadroid2/cameraupload/GalleryBucketUtils.java, app/src/main/java/com/seafile/seadroid2/cameraupload/WhatToUploadFragment.java, app/src/main/java/com/seafile/seadroid2/data/StorageManager.java, app/src/main/java/com/seafile/seadroid2/gallery/ImageManager.java, app/src/main/java/com/seafile/seadroid2/util/SeafileLog.java, app/src/main/java/com/seafile/seadroid2/util/Utils.java, app/src/main/res/layout/bucket_item.xml, app/src/main/res/layout/cuc_local_directory_fragment.xml
=> albumClassification

app/build.gradle, app/src/main/AndroidManifest.xml, app/src/main/java/com/seafile/seadroid2/SettingsManager.java, app/src/main/java/com/seafile/seadroid2/cameraupload/BucketsSelectionFragment.java, app/src/main/java/com/seafile/seadroid2/cameraupload/CameraUploadConfigActivity.java, app/src/main/java/com/seafile/seadroid2/ui/adapter/GalleryAdapter.java, app/src/main/java/com/seafile/seadroid2/ui/adapter/SeafItemAdapter.java, app/src/main/java/com/seafile/seadroid2/ui/adapter/StarredItemAdapter.java, app/src/main/java/com/seafile/seadroid2/ui/fragment/SettingsFragment.java, app/src/main/java/com/seafile/seadroid2/util/GlideCache.java, app/src/main/res/xml/settings.xml
Advanced options to modify upload Settings
=> AdvancedOptionsSettings

app/build.gradle, app/src/main/java/com/seafile/seadroid2/SeadroidApplication.java, app/src/main/java/com/seafile/seadroid2/data/StorageManager.java, app/src/main/java/com/seafile/seadroid2/gallery/ImageManager.java, app/src/main/java/com/seafile/seadroid2/util/GlideCache.java, app/src/main/java/com/seafile/seadroid2/util/SeafileLog.java, app/src/main/java/com/seafile/seadroid2/util/Utils.java
=> ModifyCachePath

app/build.gradle, app/src/main/AndroidManifest.xml, app/src/main/java/com/seafile/seadroid2/SeadroidApplication.java, app/src/main/java/com/seafile/seadroid2/SettingsManager.java, app/src/main/java/com/seafile/seadroid2/ui/activity/AccountsActivity.java, app/src/main/java/com/seafile/seadroid2/ui/activity/PrivacyPolicyActivity.java, app/src/main/java/com/seafile/seadroid2/ui/dialog/PolicyDialog.java, app/src/main/java/com/seafile/seadroid2/ui/fragment/SettingsFragment.java, app/src/main/res/drawable/policy_dialog_style.xml, app/src/main/res/layout/policy_dialog.xml, app/src/main/res/layout/privacypolicy_activity_layout.xml, app/src/main/res/values/styles.xml, app/src/main/res/xml/settings.xml
Add privacy policy in Chinese environment
=> AddPrivacyPolicy

app/build.gradle, app/src/main/java/com/seafile/seadroid2/cameraupload/BucketsSelectionFragment.java, app/src/main/java/com/seafile/seadroid2/cameraupload/CameraSyncAdapter.java, app/src/main/java/com/seafile/seadroid2/cameraupload/GalleryBucketUtils.java, app/src/main/java/com/seafile/seadroid2/util/Utils.java
Distinguish album queries smaller than the Android 10 version
=> DistinguishAlbumQueries

app/build.gradle, app/src/main/java/com/seafile/seadroid2/editor/EditorActivity.java
FileMonitorService is not running, start it in EditorActivity
=> RestartFileMonitorService

app/build.gradle, app/src/main/java/com/seafile/seadroid2/ui/dialog/GetShareLinkDialog.java
modify the logic of obtaining a share link
=> modifyShareLink

app/build.gradle, app/src/main/java/com/seafile/seadroid2/util/Utils.java
Add an AsciiDoc file to be editable as a plain text file
=> EditAsciiDocFile

app/build.gradle, app/src/main/AndroidManifest.xml
updated the issue of getting share list
=> GetShareList

app/src/main/java/com/seafile/seadroid2/ssl/SSLSeafileSocketFactory.java
=> Enable TLSv1.3

app/src/main/java/com/seafile/seadroid2/ui/dialog/PasswordDialog.java, app/src/main/res/layout/dialog_password.xml
Adds the ability to show/hide a password when opening a protected Repo.
=> Implement ShowPass on Repo Dialog
